export const WorkflowErrors = {
	WORKFLOW_NOT_FOUND: "WORKFLOW_NOT_FOUND",
	INVALID_DEFINITION: "INVALID_DEFINITION",
	MAX_CYCLES_EXCEEDED: "MAX_CYCLES_EXCEEDED",
	GATE_PENDING: "GATE_PENDING",
	ALREADY_RUNNING: "ALREADY_RUNNING",
	NOT_RUNNING: "NOT_RUNNING",
} as const;

export const AgentErrors = {
	SPAWN_FAILED: "SPAWN_FAILED",
	AGENT_NOT_FOUND: "AGENT_NOT_FOUND",
	TMUX_ERROR: "TMUX_ERROR",
	NUDGE_FAILED: "NUDGE_FAILED",
	SESSION_EXISTS: "SESSION_EXISTS",
} as const;

export const TaskStoreErrors = {
	TASK_NOT_FOUND: "TASK_NOT_FOUND",
	INVALID_TRANSITION: "INVALID_TRANSITION",
	WRITE_FAILED: "WRITE_FAILED",
	READ_FAILED: "READ_FAILED",
	PARSE_ERROR: "PARSE_ERROR",
	VALIDATION_ERROR: "VALIDATION_ERROR",
	INVALID_ID: "INVALID_ID",
} as const;

export const CLIErrors = {
	NOT_INITIALIZED: "NOT_INITIALIZED",
	CONFIG_ERROR: "CONFIG_ERROR",
} as const;
